name: Client Setup Automation

on:
  workflow_dispatch:
    inputs:
      client_name:
        description: 'Client/Company Name'
        required: true
        type: string
      client_email:
        description: 'Client Email Address'
        required: true
        type: string
      client_domain:
        description: 'Client Domain (without https://)'
        required: true
        type: string
      client_phone:
        description: 'Client Phone Number'
        required: false
        type: string
      client_address:
        description: 'Client Business Address'
        required: false
        type: string

jobs:
  customize-for-client:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create client customization branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b client-setup-${{ github.run_number }}

    - name: Replace placeholders in documentation
      run: |
        # Replace placeholders in key files
        sed -i 's/\[CLIENT_NAME\]/${{ github.event.inputs.client_name }}/g' README.md
        sed -i 's/\[CLIENT_EMAIL\]/${{ github.event.inputs.client_email }}/g' README.md
        sed -i 's/\[CLIENT_DOMAIN\]/${{ github.event.inputs.client_domain }}/g' README.md
        
        # Update package.json
        sed -i 's/\[CLIENT_NAME\]/${{ github.event.inputs.client_name }}/g' package.json
        sed -i 's/\[CLIENT_DOMAIN\]/${{ github.event.inputs.client_domain }}/g' package.json

    - name: Replace placeholders in source code
      run: |
        # Update translation files
        sed -i 's/\[CLIENT_NAME\]/${{ github.event.inputs.client_name }}/g' public/locales/en/common.json
        sed -i 's/\[CLIENT_EMAIL\]/${{ github.event.inputs.client_email }}/g' public/locales/en/common.json
        
        if [ -n "${{ github.event.inputs.client_phone }}" ]; then
          sed -i 's/\[CLIENT_PHONE\]/${{ github.event.inputs.client_phone }}/g' public/locales/en/common.json
        fi
        
        if [ -n "${{ github.event.inputs.client_address }}" ]; then
          sed -i 's/\[CLIENT_ADDRESS\]/${{ github.event.inputs.client_address }}/g' public/locales/en/common.json
        fi

    - name: Update index.html meta tags
      run: |
        sed -i 's/\[CLIENT_NAME\]/${{ github.event.inputs.client_name }}/g' index.html
        sed -i 's/\[CLIENT_DOMAIN\]/${{ github.event.inputs.client_domain }}/g' index.html

    - name: Install dependencies and test
      run: |
        npm ci
        npm run build

    - name: Commit changes
      run: |
        git add -A
        git commit -m "Client setup: ${{ github.event.inputs.client_name }}"
        git push origin client-setup-${{ github.run_number }}

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: client-setup-${{ github.run_number }}
        destination_branch: main
        pr_title: "Client Setup: ${{ github.event.inputs.client_name }}"
        pr_body: |
          ## Client Customization Complete 🎉
          
          This PR contains the automatic client setup for **${{ github.event.inputs.client_name }}**.
          
          ### Changes Made:
          - ✅ Company name: `${{ github.event.inputs.client_name }}`
          - ✅ Email: `${{ github.event.inputs.client_email }}`
          - ✅ Domain: `${{ github.event.inputs.client_domain }}`
          ${{ github.event.inputs.client_phone && format('- ✅ Phone: `{0}`', github.event.inputs.client_phone) || '' }}
          ${{ github.event.inputs.client_address && format('- ✅ Address: `{0}`', github.event.inputs.client_address) || '' }}
          
          ### Next Steps:
          1. Review the changes in this PR
          2. Test the build: `npm run build`
          3. Check the preview deployment
          4. Merge when ready
          5. Follow the [LAUNCH_CHECKLIST.md](./LAUNCH_CHECKLIST.md)
          
          ### Files Modified:
          - `README.md` - Updated project information
          - `package.json` - Updated package metadata
          - `public/locales/en/common.json` - Updated client content
          - `index.html` - Updated meta tags and SEO
          
          Generated by GitHub Actions workflow 🤖
